# Generated by Django 4.2.6 on 2024-01-05 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shrimp_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpspecies',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shrimpspecies',
            name='delete_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='shrimpspecies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
