# Generated by Django 4.2.6 on 2024-01-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShrimpFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('food_Name', models.TextField(max_length=255)),
                ('food_description', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShrimpPonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pond_number', models.IntegerField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_FName', models.TextField(max_length=255)),
                ('user_LName', models.TextField(max_length=255)),
                ('user_Username', models.TextField(max_length=255)),
                ('user_Password', models.IntegerField(max_length=10)),
                ('user_Role', models.IntegerField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShrimpSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.shrimpfoods')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShrimpPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(max_length=9999)),
                ('ShrimpSpeciesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.shrimpspecies')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.users')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShrimpPondsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shrimp_Quantity', models.IntegerField(max_length=100)),
                ('Shrimp_Weight', models.IntegerField(max_length=100)),
                ('pond_DissolvedOxygen', models.FloatField(max_length=100)),
                ('pond_WaterHardness', models.FloatField(max_length=100)),
                ('pond_pH', models.FloatField(max_length=100)),
                ('pond_Temperature', models.FloatField(max_length=100)),
                ('pond_TotalDays', models.IntegerField(max_length=100)),
                ('food_Quantity', models.FloatField(max_length=100)),
                ('growth_Rate', models.FloatField(max_length=100)),
                ('survival_Rate', models.FloatField(max_length=100)),
                ('total_Date', models.IntegerField(max_length=100)),
                ('pondID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.shrimpponds')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shrimpponds',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.users'),
        ),
        migrations.AddField(
            model_name='shrimpfoods',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.users'),
        ),
        migrations.CreateModel(
            name='ShrimpDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('disease_Name', models.TextField(max_length=255)),
                ('disease_Symptom', models.TextField(max_length=255)),
                ('disease_Cause', models.TextField(max_length=255)),
                ('disease_Prevent', models.TextField(max_length=255)),
                ('disease_Treat', models.TextField(max_length=255)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_model.users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
