# Generated by Django 4.2.6 on 2024-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0002_alter_shrimpdiseases_userid_alter_shrimpfoods_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpdiseases',
            name='disease_Image',
            field=models.ImageField(blank=True, null=True, upload_to='shrimp_diseases_images'),
        ),
        migrations.AddField(
            model_name='shrimpfoods',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='shrimp_foods_images'),
        ),
        migrations.AddField(
            model_name='shrimpspecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shrimp_species_images'),
        ),
        migrations.AlterField(
            model_name='shrimpponds',
            name='pond_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='Shrimp_Weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='pond_TotalDays',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='shrimp_Quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='total_Date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shrimpprices',
            name='price',
            field=models.IntegerField(),
        ),
    ]
