# Generated by Django 4.2.6 on 2024-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0004_rename_disease_cause_shrimpdiseases_disease_cause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shrimpdiseases',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shrimpfoods',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shrimpponds',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shrimppondsdetail',
            old_name='pond_TotalDays',
            new_name='pond_totalDays',
        ),
        migrations.RenameField(
            model_name='shrimppondsdetail',
            old_name='shrimp_Quantity',
            new_name='shrimp_quantity',
        ),
        migrations.RenameField(
            model_name='shrimpprices',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shrimpspecies',
            old_name='userId',
            new_name='user',
        ),
    ]
