# Generated by Django 4.2.6 on 2024-03-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0005_rename_userid_shrimpdiseases_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimpspecies',
            name='specie_food',
            field=models.TextField(max_length=255),
        ),
    ]
