# Generated by Django 4.2.6 on 2024-03-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0007_rename_pondid_shrimppondsdetail_pond'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpponds',
            name='pond_name',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
