# Generated by Django 4.2.6 on 2024-03-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0008_shrimpponds_pond_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimpponds',
            name='pond_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
