# Generated by Django 4.2.6 on 2024-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0009_alter_shrimpponds_pond_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimpponds',
            name='pond_number',
            field=models.CharField(max_length=32),
        ),
    ]
