# Generated by Django 4.2.6 on 2024-03-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0010_alter_shrimpponds_pond_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimpponds',
            name='pond_number',
        ),
    ]
