# Generated by Django 4.2.6 on 2024-03-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0012_remove_shrimpprices_shrimpspeciesid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimpprices',
            name='user',
        ),
    ]
