# Generated by Django 4.2.6 on 2024-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0013_remove_shrimpprices_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimpprices',
            name='price',
        ),
        migrations.AddField(
            model_name='shrimpprices',
            name='price_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shrimpprices',
            name='price_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
