# Generated by Django 4.2.6 on 2024-03-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0014_remove_shrimpprices_price_shrimpprices_price_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpprices',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
