# Generated by Django 4.2.6 on 2024-07-31 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_model', '0015_shrimpprices_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpdiseases',
            name='allow_show',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='shrimpfoods',
            name='allow_show',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='shrimpspecies',
            name='allow_show',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('information_name', models.TextField(max_length=255)),
                ('information_description', models.TextField(max_length=255)),
                ('allow_show', models.BooleanField(null=True)),
                ('information_image', models.ImageField(blank=True, null=True, upload_to='shrimp_species_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
