# Generated by Django 4.2.6 on 2024-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0016_shrimpdiseases_allow_show_shrimpfoods_allow_show_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimppondsdetail',
            name='pond_totalDays',
        ),
        migrations.AddField(
            model_name='shrimpponds',
            name='pond_totalDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shrimppondsdetail',
            name='TAN',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shrimppondsdetail',
            name='alkalinity',
            field=models.FloatField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='shrimppondsdetail',
            name='nitrite',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shrimppondsdetail',
            name='salinity',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shrimppondsdetail',
            name='transperency',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='pond_waterHardness',
            field=models.FloatField(max_length=10000),
        ),
    ]
