# Generated by Django 4.2.6 on 2024-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0017_remove_shrimppondsdetail_pond_totaldays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimpponds',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shrimpponds',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shrimpponds',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='shrimppondsdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shrimppondsdetail',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='shrimppondsdetail',
            name='transperency',
        ),
        migrations.RemoveField(
            model_name='shrimppondsdetail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shrimppondsdetail',
            name='transparency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='TAN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='alkalinity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='food_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='growth_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='nitrite',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='pond_dissolvedOxygen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='pond_pH',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='pond_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='pond_waterHardness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='salinity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='survival_rate',
            field=models.FloatField(),
        ),
    ]
