# Generated by Django 4.2.6 on 2024-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0018_remove_shrimpponds_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimpponds',
            name='pond_totalDays',
            field=models.IntegerField(),
        ),
    ]
