# Generated by Django 4.2.6 on 2024-08-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0019_alter_shrimpponds_pond_totaldays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimpponds',
            name='pond_totalDays',
            field=models.IntegerField(null=True),
        ),
    ]
