# Generated by Django 4.2.6 on 2024-08-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0020_alter_shrimpponds_pond_totaldays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimpponds',
            name='pond_totalDays',
        ),
    ]
