# Generated by Django 4.2.6 on 2024-10-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0023_shrimpponds_created_at_shrimpponds_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpponds',
            name='pond_address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shrimpponds',
            name='pond_image',
            field=models.ImageField(blank=True, null=True, upload_to='shrimp_ponds_images'),
        ),
    ]
