# Generated by Django 4.2.6 on 2024-10-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0024_shrimpponds_pond_address_shrimpponds_pond_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='shrimp_weight',
            field=models.FloatField(),
        ),
    ]
