# Generated by Django 4.2.6 on 2025-01-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0026_shrimpponds_pond_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimppondsdetail',
            name='predicted_growth_rate',
            field=models.FloatField(null=True),
        ),
    ]
