# Generated by Django 4.2.6 on 2025-01-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0027_shrimppondsdetail_predicted_growth_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimppondsdetail',
            name='growth_rate',
            field=models.FloatField(null=True),
        ),
    ]
