# Generated by Django 4.2.6 on 2025-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0029_shrimppondsdetail_predicted_growth_rate_date_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimpprices',
            name='predict',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
